# Generated by Django 3.2.5 on 2021-07-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuzy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuz',
            options={'verbose_name': 'Wszystkie tuzy', 'verbose_name_plural': 'Wszystkie tuzy'},
        ),
        migrations.AddField(
            model_name='tuz',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
