# Generated by Django 3.2.3 on 2021-07-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuzy', '0002_auto_20210723_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuz',
            name='slug',
        ),
    ]
